[package]
name = "audis"
version = "0.1.0"
authors = ["James Hunt <james@niftylogic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.redis]
version = "0.13"

[dev-dependencies.rand]
version = "0.7"
